name: "Secrets Vault"
description: "Manage secrets alongside code with Ansible Vault"
author: "Dave Cridland"
inputs:
  vault-key:
    description: "Vault key (password) for the vault file(s)"
    required: true
  environment:
    description: "A deployment environment, like main or production"
    required: false
    default: "main"
outputs:
  some-output:
    description: "Outputs vary, they are generated dynamically from the vault contents"
runs:
  using: "docker"
  image: "Dockerfile"
