name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        uses: dwd/secrets-vault@master
        with:
          value_key: secret # Would normally be a Github Secret, probably the only one.
          environment: prod-eu # Optional; defaults to `main`.

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.test }}" == "Hello world"
