name: Lint
on: [push, pull_request]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"

      - uses: actions/checkout@v1

      - name: Pipenv
        run: |
          pip install pipenv
          pipenv requirements --dev >requirements.txt

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Flake8
        run: |
          flake8 --ignore=E501 main.py gh

      - name: MyPy
        run: |
          mypy main.py gh
